name: ngs
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - pip
  - pip:
    - plotnado[toml]>=0.3,<0.4
    - tracknado>=0.3.1,<0.4.0
  - bowtie2
  - coreutils
  - samtools>1.7
  - trim-galore
  - fastqc
  - multiqc
  - seaborn
  - click
  - cookiecutter
  - ucsc-bedtobigbed
  - ucsc-bedgraphtobigwig
  - snakemake
  - numpy>=1.19
