jobname: smk-{jobid}-{rule}-{wildcards}
drmaa: --cpus-per-task={threads} --mem-per-cpu={resources.mem_mb} --time=24:00:00
use-singularity: true
singularity-args: -B /ceph -B /databank -B /datashare
jobs: 50
keep-going: True
rerun-incomplete: True
printshellcmds: True
latency-wait: 30
show-failed-logs: True
cores: 8
