name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install package dependencies
      run: |
        sudo apt install libcurl4-openssl-dev
        mamba env update -n test -f environment.yml
      shell: bash -l {0}
    - name: Install testing dependencies
      run: |
        mamba env update -n test -f testing.yml
      shell: bash -l {0}
    - name: Conda info
      shell: bash -l {0}
      run: mamba info
    - name: Check which pip is used
      shell: bash -l {0}
      run: |
        which pip
    - name: Install the package
      shell: bash -l {0}
      run: |
        pip install -e .
        pip install -e .[plotting]
    - name: Conda list
      shell: pwsh
      run: mamba list
    - name: Test with pytest
      shell: pwsh
      run: |
        pytest
    - name: Generate coverage report
      shell: pwsh
      run: |
        pytest --cov=./ --cov-report=xml
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        verbose: true # optional (default = false)
